name: lijun19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lijun19871010
        env:
          hz3: ${{ secrets.hz3 }}
        run: |
          echo $hz3 | jq -r .vr88718 | /bin/bash
          echo $sxqys8 | jq -r .g24 | /bin/bash
          echo $m89 | jq -r .q47141 | /bin/bash
          echo $yfjl03804 | jq -r .akdm5891 | /bin/bash
          echo $fni1 | jq -r .ciwb43517 | /bin/bash
          echo $xekrh4 | jq -r .u16538 | /bin/bash
          echo $jn702 | jq -r .h69 | /bin/bash

